matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=2.7
  - os: osx
    language: generic
    env: PYTHON=3.5.4
  - os: osx
    language: generic
    env: PYTHON=3.6.3

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline

    # install pyenv
    git clone --depth 1 https://github.com/pyenv/pyenv ~/.pyenv
    PYENV_ROOT="$HOME/.pyenv"
    PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"

    # set up Python environment
    pyenv install $PYTHON
    pyenv global $PYTHON
    
    pyenv rehash
    python -m pip install virtualenv
    python -m virtualenv ~/.venv
    source ~/.venv/bin/activate
  fi

install:
    # A manual check that the correct version of Python is running.
  - python --version
  - python -m pip install --disable-pip-version-check --upgrade pip
  - python -m easy_install -U setuptools

script:
  # Build the compiled extension
  - python setup.py install
  # Run the project tests
  - python tests/appveyor_test_cases.py

after_success:
  # If tests are successful, create binary packages for the project.
  - python setup.py bdist_wheel
  - python setup.py sdist
  - ls dist